### ISSUE TITLE
Do you know of this?

### ISSUE THREAD

**Issue by DictumMortuum** [alexballas/vaultlib#1]
https://pkg.go.dev/github.com/hashicorp/vault/api?utm_source=godoc

I already use this in: ssh://git@stash.int.openbet.com:7999/~draviolo/ob.git

**Comment by alexballas** [comment]
Thanks,
I updated the code to use the vault api instead.
https://github.com/alexballas/vaultlib/commit/285240453e43c1ca796a47c6c6e8e06a83f9f532
